configuration:
  - Release
  - Debug

image:
  - Visual Studio 2019
  - Visual Studio 2015
  - Visual Studio 2013

platform:
  - x64
  - x86

build_script:
  # use a few differing arguments depending on VS version to excercise different options during builds
  - ps: if ($Env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2019') { .\scripts\build-windows.ps1 -STATIC_LINK_SSL "ON" -CXX11 "ON" -UNIT_TESTS "OFF" }
  - ps: if ($Env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2015') { .\scripts\build-windows.ps1 -STATIC_LINK_SSL "ON" -CXX11 "ON" -UNIT_TESTS "ON" }
  - ps: if ($Env:APPVEYOR_BUILD_WORKER_IMAGE -eq 'Visual Studio 2013') { .\scripts\build-windows.ps1 -STATIC_LINK_SSL "OFF" -CXX11 "OFF" -UNIT_TESTS "OFF" }

test_script:
  - ps: if ( $Env:RUN_UNIT_TESTS ) { ctest --extra-verbose -C $Env:CONFIGURATION }
  
after_build:
- cmd: >-
    scripts/gather-package.bat
        7z a SRT-%APPVEYOR_REPO_BRANCH%-%CONFIGURATION%-Win%PLATFORM%-%VS_VERSION%-%APPVEYOR_BUILD_VERSION%.zip %APPVEYOR_BUILD_FOLDER%\package\*
        appveyor PushArtifact SRT-%APPVEYOR_REPO_BRANCH%-%CONFIGURATION%-Win%PLATFORM%-%VS_VERSION%-%APPVEYOR_BUILD_VERSION%.zip
